In [146]:
import pandas as pd
import numpy as np

In [147]:
demo = pd.read_csv('C:/Users/Мария/Documents/demo.csv', sep='\t')

In [148]:
demo.head()

             SubjectID        Weight  gender age  educ  work
0  1585271561336716230   2647.249658       1  60     3   1.0
1  1585271561337034143   2751.494710       1  70     3   2.0
2  1585271561337052048   1265.847051       2  40     3   1.0
3  3386713771679532483   6235.815711       1  33     3   1.0
4  8079470792529455296  13250.468637       2  20     2   2.0

In [149]:
demo.describe()

          SubjectID        Weight        gender          educ          work
count  2.637200e+04  26372.000000  26372.000000  26372.000000  26370.000000
mean   3.992888e+18   8075.419005      1.502275      2.390035      1.338453
std    2.632815e+18   8592.273886      0.500004      0.488544      0.473192
min    4.844634e+12   1101.169068      1.000000     -2.000000      1.000000
25%    1.585272e+18   2781.066294      1.000000      2.000000      1.000000
50%    3.530829e+18   5222.113486      2.000000      2.000000      1.000000
75%    6.341074e+18   9932.484591      2.000000      3.000000      2.000000
max    9.090012e+18  78324.330608      2.000000      3.000000      2.000000

In [150]:
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26372 entries, 0 to 26371
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SubjectID  26372 non-null  int64
 1   Weight     26372 non-null  float64
 2   gender     26372 non-null  int64
 3   age        26372 non-null  object
 4   educ       26372 non-null  int64
 5   work       26370 non-null  float64
dtypes: float64(2), int64(3), object(1)
memory usage: 1.2+ MB

In [151]:
demo[demo['age'] != '.']['age'].astype(int).median()

45.0

In [154]:
demo.loc[demo['age'] == '.', 'age'] = demo[demo['age'] != '.']['age'].astype(int).median() # ok

In [153]:
demo['age'] = demo['age'].astype(int)

In [155]:
demo.gender.unique()

array([1, 2], dtype=int64)

In [156]:
demo.educ.unique()

array([ 3,  2, -2], dtype=int64)

In [157]:
demo.loc[demo['educ'] == -2, 'educ'] = 3

In [158]:
demo['educ_1'] = demo['educ'] - 1

In [159]:
demo['educ_1'].head()

0    2
1    2
2    2
3    2
4    1
Name: educ_1, dtype: int64

In [160]:
demo.groupby(['educ', 'educ_1']).count().reset_index()

   educ  educ_1  SubjectID  Weight  gender    age   work
0     2       1      16081   16081   16081  16081  16080
1     3       2      10291   10291   10291  10291  10290

In [161]:
demo['educ_2'] = demo['educ'].apply(lambda x: x - 1)

In [162]:
demo['educ_2'].head()

0    2
1    2
2    2
3    2
4    1
Name: educ_2, dtype: int64

In [163]:
demo.work.unique()

array([ 1.,  2., nan])

In [164]:
demo['work'] = demo['work'].fillna(1)

In [165]:
# 12-24 25-44 45-54 55+
def f(x):
    if x > 54:
        return 5
    if x > 44:
        return 4
    if x > 24:
        return 3
    if x > 11:
        return 2
    return 1

In [166]:
demo['age_group'] = demo['age'].apply(lambda x: f(x))

In [167]:
demo['age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 26372 entries, 0 to 26371
Series name: age
Non-Null Count  Dtype
--------------  -----
26372 non-null  int32
dtypes: int32(1)
memory usage: 103.1 KB

In [168]:
demo['age_group'].head()

0    5
1    5
2    3
3    3
4    2
Name: age_group, dtype: int64

In [169]:
demo.groupby(['age', 'age_group']).count().reset_index()[['age', 'age_group']]

    age  age_group
0    12          2
1    13          2
2    14          2
3    15          2
4    16          2
..  ...        ...
76   88          5
77   89          5
78   90          5
79   93          5
80   97          5

[81 rows x 2 columns]

In [170]:
demo.groupby(['age_group']).max().reset_index()[['age', 'age_group']]

   age  age_group
0   24          2
1   44          3
2   54          4
3   97          5

In [171]:
demo.groupby(['age_group']).min().reset_index()[['age', 'age_group']]

   age  age_group
0   12          2
1   25          3
2   45          4
3   55          5

In [172]:
demo[demo['age'] != '.']['age'].astype(int).min() # min

12

In [191]:
df = demo.groupby(['age_group'])['age'].count().reset_index()

In [203]:
df.head()

   age_group       cnt
0          2  0.085014
1          3  0.408236
2          4  0.258077
3          5  0.248673

In [196]:
df['cnt'] = df['age']

In [198]:
df = df[['age_group', 'cnt']]

In [199]:
df['cnt'] /= demo['age'].size

C:\Users\Мария\AppData\Local\Temp\ipykernel_12032\1255805310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cnt'] /= demo['age'].size

In [202]:
df['cnt']

0    0.085014
1    0.408236
2    0.258077
3    0.248673
Name: cnt, dtype: float64

In [206]:
demo = pd.merge(demo, df, on='age_group', how='inner')

In [209]:
demo = demo[['SubjectID', 'Weight', 'gender', 'age', 'educ', 'work', 'educ_1', 'educ_2', 'age_group', 'cnt_y']]

In [208]:
demo.size

290092

In [210]:
demo.head()

,SubjectID,Weight,gender,age,educ,work,educ_1,educ_2,age_group,cnt_y
0,1585271561336716230,2647.249658,1,60,3,1.0,2,2,5,0.248673
1,1585271561337034143,2751.494710,1,70,3,2.0,2,2,5,0.248673
2,360293909705804547,6523.999562,1,65,2,2.0,1,1,5,0.248673
3,1585271561336816437,2720.114298,2,56,3,1.0,2,2,5,0.248673
4,1585271561336869471,3696.402261,2,55,3,1.0,2,2,5,0.248673